// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Teacher.proto

package com.tenglu.ch10;

public interface TeacherRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tenglu.ch10.TeacherRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
