// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Teacher.proto

package com.tenglu.ch10;

public interface TeacherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.tenglu.ch10.TeacherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string realname = 2;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>optional string realname = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
