// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Teacher.proto

package com.tenglu.ch10;

public final class TeacherInfo {
  private TeacherInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tenglu_ch10_MyRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tenglu_ch10_MyRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tenglu_ch10_MyResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tenglu_ch10_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTeacher.proto\022\017com.tenglu.ch10\"\035\n\tMyRe" +
      "quest\022\020\n\010username\030\001 \001(\t\"\036\n\nMyResponse\022\020\n" +
      "\010realname\030\002 \001(\t2d\n\016TeacherService\022R\n\025Get" +
      "RealNameByUsername\022\032.com.tenglu.ch10.MyR" +
      "equest\032\033.com.tenglu.ch10.MyResponse\"\000B\"\n" +
      "\017com.tenglu.ch10B\013TeacherInfoH\001P\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_tenglu_ch10_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tenglu_ch10_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tenglu_ch10_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_tenglu_ch10_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tenglu_ch10_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tenglu_ch10_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
