// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Teacher.proto

package com.tenglu.ch10;

public final class TeacherPtoro {
  private TeacherPtoro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tenglu_ch10_TeacherRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tenglu_ch10_TeacherRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tenglu_ch10_TeacherResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tenglu_ch10_TeacherResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTeacher.proto\022\017com.tenglu.ch10\"\"\n\016Teac" +
      "herRequest\022\020\n\010username\030\001 \001(\t\"#\n\017TeacherR" +
      "esponse\022\020\n\010realname\030\002 \001(\t2n\n\016TeacherServ" +
      "ice\022\\\n\025GetRealNameByUsername\022\037.com.tengl" +
      "u.ch10.TeacherRequest\032 .com.tenglu.ch10." +
      "TeacherResponse\"\000B#\n\017com.tenglu.ch10B\014Te" +
      "acherPtoroH\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_tenglu_ch10_TeacherRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tenglu_ch10_TeacherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tenglu_ch10_TeacherRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_tenglu_ch10_TeacherResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_tenglu_ch10_TeacherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tenglu_ch10_TeacherResponse_descriptor,
        new java.lang.String[] { "Realname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
